version: 1.0.'{build}'
image: Visual Studio 2017

branches:
  only:
    - master

skip_tags: true
skip_non_tags: true
skip_branch_with_pr: true
platform: x64
configuration: Release

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

build_script:
  - cd src\main\native
  - mkdir build && cd build
  - cmake -GNinja -DCMAKE_BUILD_TYPE=Release ..
  - ninja
  - if not exist "..\..\resources\META-INF" mkdir -p "..\..\resources\META-INF"
  - copy wf-exec.dll "..\..\resources\META-INF"
  - cd ..\..\..\..
  - mvn -B -DskipTests -q clean package

test_script:
  - mvn -q surefire-report:report

after_test:
  - ps: |
        $wc = New-Object 'System.Net.WebClient'
        Get-ChildItem . -Name -Recurse 'TEST-*.xml'  |
        Foreach-Object {
            $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $_))
        }

artifacts:
  - path: target\wf-exec-1.1.0.jar
    name: wf-exec library
